"""
test_byte_equality_v1.py \u2014 THE GATE.

This is the single architectural lock for Iteration 1 onward. Every iteration
from 1 to 12 must keep this test green. If it fails, the iteration is rejected.

WHAT IT ASSERTS:
  Given the exact V1 input fixture (India-US textiles, $1M, 24mo, SOFR+250bps,
  tariff 50%, swap_now_offset=0, swap_later_offset=3), running the deterministic
  knot path (draps_client.run_simulation) reproduces V1 byte-for-byte:
    \u2022 A/B/C totals match V1 exactly (with sub-dollar tolerance for FP noise on
      individual leg components)
    \u2022 SOFR path matches V1 to 4 decimal places, all 9 points
    \u2022 swap_now_fixed_rate and swap_later_fixed_rate match V1 to 4 decimal places
    \u2022 events digest (SHA-256 of canonical-JSON-encoded events list) matches V1

PREREQUISITES:
  \u2022 DRAPS running on http://localhost:4000 (npm run server in backend/draps-backend)
  \u2022 ACTUS server on :8083 and ACTUS RiskService on :8082 (Docker containers up)
  \u2022 backend/tests/fixtures/v1-baseline/india-us-textiles.json present
    (generated by `python scripts/capture_v1_baseline.py`)

The test makes its own raw HTTP call to DRAPS (using draps_client._build_config_data
to build the body) so it can inspect the full response \u2014 in particular SOFR_PATH
and the fixed rates, which draps_client.run_simulation does not currently expose.

RUN:
    cd backend
    .venv\\Scripts\\activate       # Windows
    pytest tests/test_byte_equality_v1.py -v
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import httpx
import pytest


# Make backend/ importable when pytest is invoked from the repo root or backend/.
HERE = Path(__file__).resolve().parent
BACKEND_DIR = HERE.parent
REPO_ROOT = BACKEND_DIR.parent
sys.path.insert(0, str(BACKEND_DIR))

import draps_client  # noqa: E402
from config import settings  # noqa: E402


FIXTURE_PATH = HERE / "fixtures" / "v1-baseline" / "india-us-textiles.json"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _canonical_events_digest(events: list[dict[str, Any]]) -> str:
    """Identical canonicalisation to scripts/capture_v1_baseline.py."""
    canon = json.dumps(events, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(canon.encode("utf-8")).hexdigest()


def _extract_swap_fixed_rate(payload_json_str: str, fixed_contract_id: str) -> float | None:
    payload = json.loads(payload_json_str)
    for c in payload.get("contracts", []):
        if c.get("contractType") != "SWAPS":
            continue
        for elem in c.get("contractStructure", []) or []:
            obj = elem.get("object") or {}
            if obj.get("contractID") == fixed_contract_id:
                return float(obj["nominalInterestRate"])
    return None


# ---------------------------------------------------------------------------
# Fixtures (pytest)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def baseline() -> dict[str, Any]:
    if not FIXTURE_PATH.is_file():
        pytest.fail(
            f"Baseline fixture missing: {FIXTURE_PATH}\n"
            "Generate it with: python scripts/capture_v1_baseline.py\n"
            "(That script reads backend/local_run_artifacts/draps_response.json, "
            "which is populated by `python backend/run_draps_local.py`.)"
        )
    with FIXTURE_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def draps_response(baseline: dict[str, Any]) -> dict[str, Any]:
    """Single live POST to DRAPS for the whole module. Re-used by every assertion test."""
    config_data = draps_client._build_config_data(baseline["validated_inputs"])
    url = f"{settings.draps_mcp_url.rstrip('/')}/api/simulate"
    try:
        with httpx.Client(timeout=120.0) as client:
            resp = client.post(url, json={"configData": config_data})
    except httpx.RequestError as e:
        pytest.fail(
            f"Cannot reach DRAPS at {url}: {e}\n"
            "Start DRAPS:  cd backend/draps-backend && npm run server\n"
            "Start ACTUS:  docker compose -f actus-docker-networks/quickstart-docker-actus-rf20-local.yml up -d"
        )

    if resp.status_code != 200:
        pytest.fail(f"DRAPS returned HTTP {resp.status_code}: {resp.text[:500]}")

    data = resp.json()
    if not data.get("success"):
        pytest.fail(
            f"DRAPS returned success=false. Likely ACTUS is down on :8083. "
            f"Error: {data.get('error')}"
        )
    return data


# ---------------------------------------------------------------------------
# The tests
# ---------------------------------------------------------------------------

def test_abc_totals_match_v1(baseline: dict[str, Any], draps_response: dict[str, Any]) -> None:
    """A/B/C totals match V1 exactly (within sub-dollar FP tolerance)."""
    expected = baseline["expected"]
    tol_total = baseline["tolerances"]["totals_abs"]
    env = draps_response["environmentVariables"]

    a_actual = float(env["A_total"])
    b_actual = float(env["B_total"])
    c_actual = float(env["C_total"])

    assert abs(a_actual - expected["A_total"]) < tol_total, (
        f"A_total drift: actual={a_actual}, expected={expected['A_total']}"
    )
    assert abs(b_actual - expected["B_total"]) < tol_total, (
        f"B_total drift: actual={b_actual}, expected={expected['B_total']}"
    )
    assert abs(c_actual - expected["C_total"]) < tol_total, (
        f"C_total drift: actual={c_actual}, expected={expected['C_total']}"
    )


def test_swap_legs_match_v1(baseline: dict[str, Any], draps_response: dict[str, Any]) -> None:
    """A/B/C swap legs match V1 (sub-cent tolerance \u2014 FP noise is real here)."""
    expected = baseline["expected"]
    tol = baseline["tolerances"]["swap_legs_abs"]
    env = draps_response["environmentVariables"]

    assert abs(float(env["A_swap"]) - expected["A_swap"]) < tol
    assert abs(float(env["B_swap"]) - expected["B_swap"]) < tol
    assert abs(float(env["C_swap"]) - expected["C_swap"]) < tol


def test_sofr_path_matches_v1_to_4_decimals(
    baseline: dict[str, Any], draps_response: dict[str, Any]
) -> None:
    """SOFR path matches V1 to 4 decimal places, all 9 points, same timestamps."""
    expected_path = baseline["expected"]["sofr_path"]
    decimals = baseline["tolerances"]["sofr_decimals"]

    sofr_raw = draps_response["environmentVariables"]["SOFR_PATH"]
    actual_path = json.loads(sofr_raw)

    assert len(actual_path) == len(expected_path), (
        f"SOFR path length drift: actual={len(actual_path)} expected={len(expected_path)}"
    )
    for i, (got, want) in enumerate(zip(actual_path, expected_path)):
        assert got["time"] == want["time"], (
            f"SOFR point {i} time drift: actual={got['time']} expected={want['time']}"
        )
        got_v = round(float(got["value"]), decimals)
        want_v = round(float(want["value"]), decimals)
        assert got_v == want_v, (
            f"SOFR point {i} ({got['time']}) value drift: "
            f"actual={got_v} expected={want_v} (rounded to {decimals} decimals)"
        )


def test_swap_fixed_rates_match_v1(
    baseline: dict[str, Any], draps_response: dict[str, Any]
) -> None:
    """swap_now_fixed_rate (SWAP-B-FIXED) and swap_later_fixed_rate (SWAP-C-FIXED) match V1."""
    expected = baseline["expected"]
    decimals = baseline["tolerances"]["fixed_rate_decimals"]
    env = draps_response["environmentVariables"]

    actual_now = _extract_swap_fixed_rate(env["SWAP_NOW_PAYLOAD"], "SWAP-B-FIXED")
    actual_later = _extract_swap_fixed_rate(env["SWAP_LATER_PAYLOAD"], "SWAP-C-FIXED")

    assert actual_now is not None, "Could not extract swap_now_fixed_rate from response"
    assert actual_later is not None, "Could not extract swap_later_fixed_rate from response"

    assert round(actual_now, decimals) == round(expected["swap_now_fixed_rate"], decimals), (
        f"swap_now_fixed_rate drift: actual={actual_now} expected={expected['swap_now_fixed_rate']}"
    )
    assert round(actual_later, decimals) == round(expected["swap_later_fixed_rate"], decimals), (
        f"swap_later_fixed_rate drift: actual={actual_later} expected={expected['swap_later_fixed_rate']}"
    )


def test_events_digest_matches_v1(
    baseline: dict[str, Any], draps_response: dict[str, Any]
) -> None:
    """SHA-256 of canonical events JSON matches V1.

    NOTE: DRAPS's `simulation` array contains only the LAST scenario (C) contracts.
    The digest covers those events \u2014 enough to catch any drift in event payoffs,
    rates, and timestamps.
    """
    expected = baseline["expected"]

    events: list[dict[str, Any]] = []
    for contract in draps_response.get("simulation") or []:
        if isinstance(contract, dict) and isinstance(contract.get("events"), list):
            events.extend(contract["events"])

    assert len(events) == expected["events_count"], (
        f"events count drift: actual={len(events)} expected={expected['events_count']}"
    )

    actual_digest = _canonical_events_digest(events)
    assert actual_digest == expected["events_digest_sha256"], (
        f"events digest drift:\n"
        f"  actual:   {actual_digest}\n"
        f"  expected: {expected['events_digest_sha256']}\n"
        f"  (event count matches; payoffs/rates/timestamps have drifted)"
    )


def test_baseline_smoke(baseline: dict[str, Any]) -> None:
    """Sanity check on the fixture itself: V1 invariants we expect to hold."""
    e = baseline["expected"]
    # Hedge B (swap now) must win vs A (no hedge) in the textile-tariff baseline.
    assert e["B_total"] < e["A_total"], "B should beat A in the V1 baseline"
    # And B must beat C (V1's whole point: hedging early > waiting 3 months).
    assert e["B_total"] < e["C_total"], "B should beat C in the V1 baseline"
    # SOFR path peaks at quarter 5 (per V1 design).
    sofr_vals = [p["value"] for p in e["sofr_path"]]
    assert sofr_vals.index(max(sofr_vals)) == 4, "SOFR path should peak at the 5th quarterly point"
